name: Lint

on:
    push:
      branches:
      - main
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Setup Python
            uses: actions/setup-python@v1
            with:
              python-version: 3.7.x
              architecture: x64
          - name: Fetch Droidlet
            uses: actions/checkout@v2
            with:
              ref: ${{ github.event.pull_request.head.sha }}
              fetch-depth: 0
          - name: Fix git
            run: |
              set -eux
              git fetch origin main
              if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                git branch -f main origin/main
              fi
          - name: Run flake8
            run: |
              set -eux
              pip install -q flake8
              flake8 --version
              bash tools/codetools/check_flake8_failures.sh --ci | tee ${GITHUB_WORKSPACE}/output-annotations.txt
          - name: Add annotations
            uses: pytorch/add-annotations-github-action@master
            with:
              check_name: 'lint'
              linter_output_path: 'output-annotations.txt'
              commit_sha: ${{ github.event.pull_request.head.sha }}
              regex: '^(?<filename>.*?):(?<lineNumber>\d+):(?<columnNumber>\d+): (?<errorCode>\w+\d+) (?<errorDesc>.*)'
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
